# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-19 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='user/profile/avatar'),
        ),
    ]
