# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-18 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thread', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatethread',
            name='initiator',
            field=models.ForeignKey(help_text='User who inited conversation.', on_delete=django.db.models.deletion.CASCADE, related_name='inited_private_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatethread',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupthread',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_group_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupthread',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
