# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-27 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupthread',
            name='name',
            field=models.CharField(default='Group chat', max_length=30),
        ),
    ]
